{% set name = "hypofuzz" %}
{% set version = "24.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hypofuzz-{{ version }}.tar.gz
  sha256: ad21b1fd8c07e20bd5315cdb029be361fc5fb2e432b33b90a4de9f1660e900ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  entry_points:
    - hypothesis=hypofuzz.entrypoint

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - black >=23.3.0
    - coverage >=5.2.1
    - dash >=2.0.0
    - hypothesis >=6.121.0
    - libcst >=1.0.0
    - pandas >=1.0.0
    - psutil >=3.0.0
    - pytest >=6.0.1

    # From hypothesis[cli]
    - click >=7.0
    - rich >=9.0.0

    # Pip check reports dash 2.15 requires the following
    - dash-core-components
    - dash-html-components
    - dash-table

test:
  imports:
    - hypofuzz
  commands:
    - pip check
    - hypothesis fuzz --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://hypofuzz.com/
  dev_url: https://github.com/Zac-HD/hypofuzz
  doc_url: https://hypofuzz.com/docs/
  summary: Adaptive fuzzing for property-based tests
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
