{% set name = "hypofuzz" %}
{% set version = "25.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hypofuzz-{{ version }}.tar.gz
  sha256: 069649a808712b7724675f01df6a21a52d0a00d84dd0d74e8ba1d255eeb3a3c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
    - black >=23.3.0
    - coverage >=5.2.1
    - dash >=2.0.0
    - hypothesis >=6.93.2
    - libcst >=1.0.0
    - pandas >=1.0.0
    - psutil >=3.0.0
    - pytest >=6.0.1
    - requests >=2.24.0

    # Pip check reports dash 2.15 requires the following
    - dash-core-components
    - dash-html-components
    - dash-table

test:
  imports:
    - hypofuzz
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://hypofuzz.com/
  dev_url: https://github.com/Zac-HD/hypofuzz
  doc_url: https://hypofuzz.com/docs/
  summary: Adaptive fuzzing for property-based tests
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
