{% set name = "hypofuzz" %}
{% set version = "25.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hypofuzz-{{ version }}.tar.gz
  sha256: 0976045c122b4bfbecd508924689dc82059acd8ce7a29902d3bdc468dec593d1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
    - nodejs
  run:
    - python >={{ python_min }}
    - black >=23.3.0
    - coverage >=5.2.1
    - hypothesis >=6.125.3
    - libcst >=1.0.0
    - psutil >=3.0.0
    - pytest >=6.0.1
    - starlette
    - trio
    - hypercorn

    # From hypothesis[cli]
    - click >=7.0
    - rich >=9.0.0

test:
  imports:
    - hypofuzz
  commands:
    - pip check
    - hypothesis fuzz --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://hypofuzz.com/
  dev_url: https://github.com/Zac-HD/hypofuzz
  doc_url: https://hypofuzz.com/docs/
  summary: Adaptive fuzzing for property-based tests
  license: AGPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
